version: '3.6'

services:
  db:
    image: postgres
    #    env_file:
    #      - ../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin123}
      - POSTGRES_DB=${DB_NAME:-beertato}
      - PGUSER=${DB_USER:-admin}

  web:
    build: .
    container_name: bt
    volumes:
      - .:/bt
    ports:
      - '3000:5000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    volumes:
      - ./api:/api
    ports:
      - '3005:3005'
    depends_on:
      - db
