version: '3.6'

services:
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin123}
      - POSTGRES_DB=${DB_NAME:-beertato}
      - PGUSER=${DB_USER:-admin}

  web:
    build: .
    image: bt:latest
    volumes:
      - .:/bt
    env_file:
      - .env
    ports:
      - "3001:5000"

  api:
    build: .
    image: bt:latest
    command: /api_start.sh
    env_file:
      - .env
    ports:
      - "3005:3005"
    depends_on:
      - db
